-- local renamer = function()
--     local Input = require("nui.input")
--     local event = require("nui.utils.autocmd").event
--     local grabbed = vim.fn.expand("<cword>")
--
--     local input = Input({
--         position = "50%",
--         size = {
--             width = 20,
--         },
--         border = {
--             style = "double",
--             highlight = "FloatBorder",
--             text = {
--                 top = "Input -> " .. grabbed,
--                 top_align = "left",
--             },
--         },
--         win_options = {
--             winhighlight = "Normal:Normal,FloatBorder:Normal",
--         },
--     }, {
--         prompt = "",
--         default_value = "Hello",
--         on_close = function()
--             print("Input Closed!")
--         end,
--         on_submit = function(value)
--             print("Input Submitted: " .. value)
--         end,
--     })
--
--     -- mount/open the component
--     input:mount()
--     -- unmount component when cursor leaves buffer
--     input:on(event.BufLeave, function()
--         input:unmount()
--     end)
-- end
--
-- vim.keymap.set("n", "<leader>r", renamer)
