return {
	-- "b0o/incline.nvim",
	-- dependencies = {
	--     "SmiteshP/nvim-navic",
	-- },
	-- event = "VeryLazy",
	-- config = function()
	--     require("incline").setup({
	--         window = {
	--             padding = 0,
	--             margin = { horizontal = 0, vertical = 0 },
	--         },
	--         render = function(props)
	--             local filename = vim.fn.fnamemodify(vim.api.nvim_buf_get_name(props.buf), ":t")
	--             local modified = vim.bo[props.buf].modified
	--             return {
	--                 " ",
	--                 filename,
	--                 modified and { " *", guifg = "#888888", gui = "bold" } or "",
	--                 " ",
	--                 guibg = "#222222",
	--                 guifg = "#eeeeee",
	--             }
	--         end,
	--     })
	-- end,
}
